#! /usr/bin/env node

// ./newpost "My awesome blog post"

var nunjucks = require('nunjucks');


(function() {
 
  var fs = require('fs');
  var mkdirp = require('mkdirp');
  var blogUtil = require('./lib/utility');

  var onlyTitle = function() {
    return process.argv.length == 3;
  };

  var title, filename, permalink, date;

  if (onlyTitle()) {
    title = process.argv[2];
    filename = "./src/posts/" + blogUtil.titleToPath(title) + '.md';
    permalink = "/" + blogUtil.titleToPath(title) + '.html';
    date = "Undated"; 
  } else {
    mkdirp.sync("./src/posts/" + process.argv[2]);
    title = process.argv[3];
    date = process.argv[2];
    filename = "./src/posts/" + process.argv[2] + 
               "/" + blogUtil.titleToPath(title) + '.md';
    permalink = "/" + process.argv[2] + 
               "/" + blogUtil.titleToPath(title) + '.html';
  }

  var postText = nunjucks.render('./post-template.md', {
      permalink: permalink,
      title: title,
      date: date
  });



  fs.writeFile(filename, postText, function(err) {
      if(err) {
        return console.log(err);
      } else {
        console.log("Created! Open it with 'vim " +  filename + "'");
      }
    });

}());
