#! /usr/bin/env node

// this is how you use it
// ./newpost "2016/04/20" "My awesome blog post"
// ./newpost "My awesome blog post"

var nunjucks = require('nunjucks');


(function() {
 
  var fs = require('fs');
  var mkdirp = require('mkdirp');
  var blogUtil = require('./lib/utility');

  var onlyTitle = function() {
    return process.argv.length == 3;
  };

  var title, filename, permalink;

  if (onlyTitle()) {
    title = process.argv[2];
    filename = "./src/posts/" + blogUtil.titleToPath(title) + '.md';
    permalink = "./src/posts/" + blogUtil.titleToPath(title) + '.html';
  } else {
    mkdirp.sync("./src/posts/" + process.argv[2]);
    var title = process.argv[3];
    filename = "./src/posts/" + process.argv[2] + 
               "/" + blogUtil.titleToPath(title) + '.md';
    permalink = "./src/posts/" + process.argv[2] + 
               "/" + blogUtil.titleToPath(title) + '.html';
  }

  var postText = nunjucks.render('./post-template.md', {
      permalink: permalink,
      title:title
  });



  fs.writeFile(filename, postText, function(err) {
      if(err) {
        return console.log(err);
      } else {
        console.log("Created! Open it with 'vim " +  filename + "'");
      }
    });

}());
